<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>VoiceCommander.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="Vosk" Version="0.3.38" />
    <PackageReference Include="Whisper.net" Version="1.9.1" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VoiceCommander.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" WithCulture="false" />
  </ItemGroup>

</Project>
